name: Sync Upstream With Conflict Auto-Resolve

on:
  schedule:
    - cron: '0 */2 * * *'  # 每6小时执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/6Kmfi6HP/proxy_files.git
          git fetch upstream

      - name: Merge upstream/main (auto-resolve conflicts, allow unrelated histories)
        run: |
          git checkout main

          # Try merge with --allow-unrelated-histories
          if ! git merge upstream/main --no-edit --allow-unrelated-histories; then
            echo "Conflict occurred. Resolving in favor of upstream..."

            # Resolve all conflicts using upstream version
            for file in $(git diff --name-only --diff-filter=U); do
              echo "Resolving $file from upstream..."
              git checkout --theirs -- "$file"
              git add "$file"
            done

            git commit -m "Auto-resolved conflicts: prefer upstream"
          fi

      - name: Check if files changed
        id: detect_changes
        run: |
          if git diff --quiet origin/main; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Push updated files
        if: steps.detect_changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
